### PR TITLE
Expand README to clarify scope of this repo

### PR DESCRIPTION
**Pull request by petermao**
I followed the README, but at the end, I wasn't sure what to do next.  User would still need to install `org-noter` via `straight.el`?

Is this repo specifically for testing out `straight.el` or will we be expanding this to include other specific configs?  Or will we have separate repos for different configs, modelled on this repo?

### CODE REVIEW

**Comment by petermao** [comment]
I just noticed that we differ in where we keep out git repos.  Looks like you use `~/workspace/` while I use `~/emacs/` so the `install-straight.el` script does not work for me without modification to https://github.com/org-noter/org-noter-with-emacs-basic-test/blob/6c703536a0effdfdf5a0781974653514890b17aa/install-straight.el#L22

Is there a good way to abstract the name of the dir that holds git clones?

**Comment by dmitrym0** [comment]
After you follow the steps and run `eval-buffer` you end up with:

- straight.el
- use-package
- org
- pdf-tools
- org-noter

You've got a pristine org-noter environment unencumbered by any potential modifications in your "regular" Emacs setup. Think of it as `emacs -Q`, for org-noter testing.

The goal is to use it as a test before releases to eliminate the "works on my machine because I had a magic value set in my init.el that I forgot about". 

For maintaining correct "local" path, we can include `local-path.el` that contains

```emacs-lisp
(setq local-org-noter-development-path "~/workspace/org-noter")
```

then import it to install-straight.el and add it to `.gitignore`.

What do you think?

**Comment by petermao** [comment]
Well, for now it's just me and you (@dmitrym0)  using this repo for org noter, but I think adding a separate file that is ignored, that a new user would have to set up is a barrier to adoption.

Instead, in the two new commits, I've used `find` to locate the `with-emacs.sh` installation, temporarily binding it to `foo`.  Then the sandboxed emacs is opened with the point sitting on the dev-path to make it easy to change.

Text in the README is (hopefully) enough to guide the uninitiated.

**Comment by dmitrym0** [comment]
Ooops, I forgot about this will review asap.

**Comment by petermao** [comment]
no prob-- I had forgotten about it for a long time, too!

**Comment by dmitrym0** [comment]
This is still non trivial to get going but better than it used to be... still room to grow.

**Review by dmitrym0 — APPROVED** [review]

**Pull request merged**
